cognitive-complexity-threshold = 30
too-many-arguments-threshold = 10
type-complexity-threshold = 250
enum-variant-size-threshold = 200

# Disable specific lints
disallowed-methods = []
disallowed-types = []

# Enable pedantic lints
warn-on-all-wildcard-imports = true
